### ISSUE TITLE
git clone fails, incorrect access rights?

### ISSUE THREAD

**Issue by zaggynl** [wcedmisten/docker-openstreetmap-stack#2]
As per instructions: 

git clone git@github.com:wcedmisten/valhalla-app.git
Cloning into 'valhalla-app'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by wcedmisten** [comment]
Are you able to clone this repo? But not `valhalla-app`?

You could also try cloning with `https` or the github CLI instead:

```
git clone https://github.com/wcedmisten/valhalla-app.git
```

```
gh repo clone wcedmisten/valhalla-app
```

**Comment by zaggynl** [comment]
Thanks, noticed I was using ssh method instead of https too late!
Was able to clone via https just fine, thanks.
Hope to get this running soon after I figure out the best way to store this much data via docker volumes on separate disks/NFS share.
