### ISSUE TITLE
Headway vs Valhalla App

### ISSUE THREAD

**Issue by spammads** [wcedmisten/docker-openstreetmap-stack#6]
thanks for the write up and providing the working docker-compose.
I noticed the current master-branch of valhalla-app differs a bit from the app on your demo-site.
Can you provide the repo you used for "Headway" or are you not planning to share this?

Thanks again for the work and showcasing.

**Comment by wcedmisten** [comment]
Sorry about that! I forgot to update this repo when I changed the hosted demo app.

The current app running at [https://map-demo.wcedmisten.dev](https://map-demo.wcedmisten.dev) is:

 https://github.com/headwaymaps/headway

I also have a blog post detailing the differences if you're interested in learning more:
https://wcedmisten.fyi/post/upgrading-with-headway-maps/

**Comment by spammads** [comment]
Ah. Didnt know Headway can be used for such coverings. Thanks for the reply and your writeups.
